In [1]:
import pandas as pd 
import json

- import data
- rm duplicates
- rm NaN n NULL
- rm unused columns
- year to int

In [2]:
df = pd.read_excel("db/Salmonella-Chile-210824.xlsx")
print(df.shape[0])
df = df.dropna(subset=['cgST', 'Collection Year', 'Source Niche'])
print(df.shape[0])
df = df.drop_duplicates(subset=['cgST', 'Collection Year', 'Source Niche'])
print(df.shape[0])
df = df.drop(columns=['Uberstrain', 'Name', 'Source Niche', 'Source Type',
       'Data Source(Accession No.;Sequencing Platform;Sequencing Library;Insert Size;Experiment;Bases;Average Length;Status)',
       'Source Details', 'Collection Month', 'Collection Day',
       'Collection Time', 'Continent', 'Country', 'Region', 'District', 'City',
       'Post Code', 'Latitude', 'Longitude', 'Serovar', 'Subspecies',
       'Disease', 'Antigenic Formulas', 'Phage Type', 'Lab Contact', 'Comment',
       'Bio Project ID', 'Project ID', 'Sample ID', 'Secondary Sample ID',
       'Date Entered', 'Release Date', 'SISTR1 Serogroup',
       'SISTR1 H1', 'SISTR1 H2', 'SeqSero2 Serovar', 'SeqSero2 Serogroup',
       'SeqSero2 H1', 'SeqSero2 H2', 'ST', 'eBG', 'Serotype (Predicted)',
       'Lineage', 'Subspecies.1', 'aroC', 'dnaN', 'hemD', 'hisD', 'purE',
       'sucA', 'thrA', 'cgST', 'HC0 (indistinguishable)', 'HC2', 'HC5', 'HC10', 
       'HC100', 'HC200', 'HC400', 'HC900 (ceBG)',
       'HC2000 (Super-lineage)', 'HC2600', 'HC2850 (subsp.)', 'Status',
       'Coverage', 'N50', 'Length', 'Species', 'Contig Number(>=200 bp)',
       'Low Quality Bases', 'Version'])
print()
print(df.columns)
df["Collection Year"] = df["Collection Year"].astype(int)
print()
df.head()

2530
2474
1774

Index(['Barcode', 'Collection Year', 'SISTR1 Serovar', 'HC20', 'HC50',
       'Assembly Barcode'],
      dtype='object')

        Barcode  Collection Year SISTR1 Serovar   HC20   HC50 Assembly Barcode
0  SAL_BA2039AA             2006    Typhimurium    305    305  SAL_IA5729AA_AS
1  SAL_BA3777AA             2006         Anatum  34548      7  SAL_EA4360AA_AS
2  SAL_CA8406AA             2005        Newport  17481  17481  SAL_CA3641AA_AS
3  SAL_CA8991AA             2004    Typhimurium  14886    293  SAL_JA4500AA_AS
4  SAL_DA4911AA             1945    Typhimurium  17777   1585  SAL_JA6717AA_AS

### Frequency per year

In [3]:
year_count = df["Collection Year"].value_counts().reset_index()
year_count.columns = ["Collection Year", 'frequency']
year_count = year_count.sort_values(by='Collection Year', ascending=False)

# to export
#year_count.to_csv("out/year_count.csv", index=False) 
#print(year_count)

### Most frequent serovars

In [4]:
frequent_serovars = ['Enteritidis', 'Agona', 'Typhimurium', 'Infantis', 'Newport', 'I 1,4,[5],12:i:-']
df_only_frequent_serovars = df[df['SISTR1 Serovar'].isin(frequent_serovars)]
df_only_frequent_serovars.head()

        Barcode  Collection Year SISTR1 Serovar   HC20   HC50 Assembly Barcode
0  SAL_BA2039AA             2006    Typhimurium    305    305  SAL_IA5729AA_AS
2  SAL_CA8406AA             2005        Newport  17481  17481  SAL_CA3641AA_AS
3  SAL_CA8991AA             2004    Typhimurium  14886    293  SAL_JA4500AA_AS
4  SAL_DA4911AA             1945    Typhimurium  17777   1585  SAL_JA6717AA_AS
5  SAL_EA4185AA             2012    Enteritidis    760     87  SAL_IA5190AA_AS

### Make df_HC

In [5]:
df_only_frequent_serovars["HC20"] = df_only_frequent_serovars["HC20"].astype(str)
df_only_frequent_serovars["HC50"] = df_only_frequent_serovars["HC50"].astype(str)
df_only_frequent_serovars['SISTR1 Serovar HC20'] = df_only_frequent_serovars['SISTR1 Serovar'] + " " + df_only_frequent_serovars['HC20']
df_only_frequent_serovars['SISTR1 Serovar HC50'] = df_only_frequent_serovars['SISTR1 Serovar'] + " " + df_only_frequent_serovars['HC50']
df_HC = df_only_frequent_serovars.drop(columns=['SISTR1 Serovar', 'HC20', 'HC50']).reset_index(drop=True)
df_HC.head()

/tmp/ipykernel_101158/27270877.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_only_frequent_serovars["HC20"] = df_only_frequent_serovars["HC20"].astype(str)
/tmp/ipykernel_101158/27270877.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_only_frequent_serovars["HC50"] = df_only_frequent_serovars["HC50"].astype(str)
/tmp/ipykernel_101158/27270877.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_only_frequent_serovars['SISTR1 Serovar HC20'] = df_only_frequent_serovars['SISTR1 Serovar'] + " " + df_only_frequent_serovars['HC20']
/tmp/ipykernel_101158/27270877.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_only_frequent_serovars['SISTR1 Serovar HC50'] = df_only_frequent_serovars['SISTR1 Serovar'] + " " + df_only_frequent_serovars['HC50']

,Barcode,Collection Year,Assembly Barcode,SISTR1 Serovar HC20,SISTR1 Serovar HC50
0,SAL_BA2039AA,2006,SAL_IA5729AA_AS,Typhimurium 305,Typhimurium 305
1,SAL_CA8406AA,2005,SAL_CA3641AA_AS,Newport 17481,Newport 17481
2,SAL_CA8991AA,2004,SAL_JA4500AA_AS,Typhimurium 14886,Typhimurium 293
3,SAL_DA4911AA,1945,SAL_JA6717AA_AS,Typhimurium 17777,Typhimurium 1585
4,SAL_EA4185AA,2012,SAL_IA5190AA_AS,Enteritidis 760,Enteritidis 87

### Make json

In [6]:
def make_json(df, HC: str) -> None:
    counts = df.groupby([f'SISTR1 Serovar {HC}', 'Collection Year']).size().reset_index(name='Frequency')
    db = {}
    for _, row in counts.iterrows():
        name = row[f'SISTR1 Serovar {HC}']
        year = row['Collection Year']
        frequency = row['Frequency']
        if name not in db:
            db[name] = {}
        db[name][year] = frequency

    with open(f'out/{HC}.json', 'w') as f:
        json.dump(db, f, indent=4)

make_json(df_HC, 'HC20')
make_json(df_HC, 'HC50')

### Export df as .csv

In [7]:
df_HC.to_csv('out/df_HC.tsv', index=False, sep='\t')

### Get Barcode

In [8]:
def get_clusters(HC_selected, HC: str):
    df_only_selected = df_HC[df_HC[f'SISTR1 Serovar {HC}'].isin(HC_selected)]
    barcodes = df_only_selected[[f'SISTR1 Serovar {HC}', 'Assembly Barcode', 'Barcode']]
    barcodes.head()
    barcodes['Assembly Barcode'].to_csv(f'out/Assembly_Barcode_{HC}.csv', index=False)

##### Segun HC20

In [9]:
#   Typhimurium 777
#   Newport 108080
#   Infantis 343
#   I 1,4,[5],12:i:- 2
#   Enteritidis 760
#   Agona 419
HC20_selected = ['Typhimurium 777', 'Newport 108080', 'Infantis 343', 'I 1,4,[5],12:i:- 2', 'Enteritidis 760', 'Agona 419']
get_clusters(HC20_selected, 'HC20')

##### Segun HC50

In [10]:
#   Typhimurium 293
#   Newport 938
#   Infantis 36
#   I 1,4,[5],12:i:- 2
#   Enteritidis 87
#   Agona 29
HC50_selected = ['Typhimurium 293', 'Newport 938', 'Infantis 36', 'I 1,4,[5],12:i:- 2', 'Enteritidis 87', 'Agona 29']
get_clusters(HC50_selected, 'HC50')